package douyin

type AutoGenerated struct {
	Location string `json:"location"`
	Odin     struct {
		UserID       string `json:"user_id"`
		UserType     int    `json:"user_type"`
		UserIsAuth   int    `json:"user_is_auth"`
		UserIsLogin  int    `json:"user_is_login"`
		UserUniqueID string `json:"user_unique_id"`
	} `json:"odin"`
	RouteInitialProps struct {
		StatusCode string `json:"status_code"`
		LayoutData struct {
			CategoryTab struct {
				CategoryData []struct {
					Partition struct {
						IDStr string `json:"id_str"`
						Type  int    `json:"type"`
						Title string `json:"title"`
					} `json:"partition"`
					SubPartition []struct {
						Partition struct {
							IDStr string `json:"id_str"`
							Type  int    `json:"type"`
							Title string `json:"title"`
						} `json:"partition"`
						SubPartition []interface{} `json:"sub_partition"`
					} `json:"sub_partition"`
				} `json:"categoryData"`
				RecommendPartitions []struct {
					Partition struct {
						IDStr string `json:"id_str"`
						Type  int    `json:"type"`
						Title string `json:"title"`
					} `json:"partition"`
					SubPartition []struct {
						IDStr string `json:"id_str"`
						Type  int    `json:"type"`
						Title string `json:"title"`
					} `json:"sub_partition"`
				} `json:"recommendPartitions"`
			} `json:"categoryTab"`
			ThemeChange                int  `json:"themeChange"`
			ShowNewHeader              int  `json:"showNewHeader"`
			Collection                 int  `json:"collection"`
			SearchBarStyle             int  `json:"searchBarStyle"`
			ShowImIcon                 int  `json:"showImIcon"`
			ImShareGroup               int  `json:"imShareGroup"`
			SearchBarHistoryPanelStyle int  `json:"searchBarHistoryPanelStyle"`
			IsClient                   bool `json:"isClient"`
		} `json:"layoutData"`
	} `json:"routeInitialProps"`
	LayoutData struct {
		CategoryTab struct {
			CategoryData []struct {
				Partition struct {
					IDStr string `json:"id_str"`
					Type  int    `json:"type"`
					Title string `json:"title"`
				} `json:"partition"`
				SubPartition []struct {
					Partition struct {
						IDStr string `json:"id_str"`
						Type  int    `json:"type"`
						Title string `json:"title"`
					} `json:"partition"`
					SubPartition []interface{} `json:"sub_partition"`
				} `json:"sub_partition"`
			} `json:"categoryData"`
			RecommendPartitions []struct {
				Partition struct {
					IDStr string `json:"id_str"`
					Type  int    `json:"type"`
					Title string `json:"title"`
				} `json:"partition"`
				SubPartition []struct {
					IDStr string `json:"id_str"`
					Type  int    `json:"type"`
					Title string `json:"title"`
				} `json:"sub_partition"`
			} `json:"recommendPartitions"`
		} `json:"categoryTab"`
		ThemeChange                int  `json:"themeChange"`
		ShowNewHeader              int  `json:"showNewHeader"`
		Collection                 int  `json:"collection"`
		SearchBarStyle             int  `json:"searchBarStyle"`
		ShowImIcon                 int  `json:"showImIcon"`
		ImShareGroup               int  `json:"imShareGroup"`
		SearchBarHistoryPanelStyle int  `json:"searchBarHistoryPanelStyle"`
		IsClient                   bool `json:"isClient"`
	} `json:"layoutData"`
	InitialState struct {
		AppStore struct {
		} `json:"appStore"`
		UserStore struct {
			UserInfo struct {
			} `json:"userInfo"`
			HeaderUserInfo struct {
				Info struct {
				} `json:"info"`
			} `json:"headerUserInfo"`
			Odin struct {
				UserID       string `json:"user_id"`
				UserType     int    `json:"user_type"`
				UserIsAuth   int    `json:"user_is_auth"`
				UserIsLogin  int    `json:"user_is_login"`
				UserUniqueID string `json:"user_unique_id"`
			} `json:"odin"`
		} `json:"userStore"`
		HomeStore struct {
			SelectedRoom interface{} `json:"selectedRoom"`
		} `json:"homeStore"`
		RoomStore struct {
			RoomInfo struct {
				Room struct {
					IDStr        string `json:"id_str"`
					Status       int    `json:"status"`
					StatusStr    string `json:"status_str"`
					Title        string `json:"title"`
					UserCountStr string `json:"user_count_str"`
					Cover        struct {
						URLList []string `json:"url_list"`
					} `json:"cover"`
					StreamURL struct {
						FlvPullURL struct {
							FullHd1 string `json:"FULL_HD1"`
							Hd1     string `json:"HD1"`
							Sd1     string `json:"SD1"`
							Sd2     string `json:"SD2"`
						} `json:"flv_pull_url"`
						DefaultResolution string `json:"default_resolution"`
						HlsPullURLMap     struct {
							FullHd1 string `json:"FULL_HD1"`
							Hd1     string `json:"HD1"`
							Sd1     string `json:"SD1"`
							Sd2     string `json:"SD2"`
						} `json:"hls_pull_url_map"`
						HlsPullURL        string `json:"hls_pull_url"`
						StreamOrientation int    `json:"stream_orientation"`
						LiveCoreSdkData   struct {
							PullData struct {
								Options struct {
									DefaultQuality struct {
										Name       string `json:"name"`
										SdkKey     string `json:"sdk_key"`
										VCodec     string `json:"v_codec"`
										Resolution string `json:"resolution"`
										Level      int    `json:"level"`
									} `json:"default_quality"`
									Qualities []struct {
										Name       string `json:"name"`
										SdkKey     string `json:"sdk_key"`
										VCodec     string `json:"v_codec"`
										Resolution string `json:"resolution"`
										Level      int    `json:"level"`
									} `json:"qualities"`
								} `json:"options"`
								StreamData string `json:"stream_data"`
							} `json:"pull_data"`
						} `json:"live_core_sdk_data"`
					} `json:"stream_url"`
					MosaicStatus    int      `json:"mosaic_status"`
					MosaicStatusStr string   `json:"mosaic_status_str"`
					AdminUserIds    []int64  `json:"admin_user_ids"`
					AdminUserIdsStr []string `json:"admin_user_ids_str"`
					Owner           struct {
						IDStr       string `json:"id_str"`
						SecUID      string `json:"sec_uid"`
						Nickname    string `json:"nickname"`
						AvatarThumb struct {
							URLList []string `json:"url_list"`
						} `json:"avatar_thumb"`
						FollowInfo struct {
							FollowStatus    int    `json:"follow_status"`
							FollowStatusStr string `json:"follow_status_str"`
						} `json:"follow_info"`
					} `json:"owner"`
					RoomAuth struct {
						Chat                      bool `json:"Chat"`
						Danmaku                   bool `json:"Danmaku"`
						Gift                      bool `json:"Gift"`
						LuckMoney                 bool `json:"LuckMoney"`
						Digg                      bool `json:"Digg"`
						RoomContributor           bool `json:"RoomContributor"`
						Props                     bool `json:"Props"`
						UserCard                  bool `json:"UserCard"`
						Poi                       bool `json:"POI"`
						MoreAnchor                int  `json:"MoreAnchor"`
						Banner                    int  `json:"Banner"`
						Share                     int  `json:"Share"`
						UserCorner                int  `json:"UserCorner"`
						Landscape                 int  `json:"Landscape"`
						LandscapeChat             int  `json:"LandscapeChat"`
						PublicScreen              int  `json:"PublicScreen"`
						GiftAnchorMt              int  `json:"GiftAnchorMt"`
						RecordScreen              int  `json:"RecordScreen"`
						DonationSticker           int  `json:"DonationSticker"`
						HourRank                  int  `json:"HourRank"`
						CommerceCard              int  `json:"CommerceCard"`
						AudioChat                 int  `json:"AudioChat"`
						DanmakuDefault            int  `json:"DanmakuDefault"`
						KtvOrderSong              int  `json:"KtvOrderSong"`
						SelectionAlbum            int  `json:"SelectionAlbum"`
						Like                      int  `json:"Like"`
						MultiplierPlayback        int  `json:"MultiplierPlayback"`
						DownloadVideo             int  `json:"DownloadVideo"`
						Collect                   int  `json:"Collect"`
						TimedShutdown             int  `json:"TimedShutdown"`
						Seek                      int  `json:"Seek"`
						Denounce                  int  `json:"Denounce"`
						Dislike                   int  `json:"Dislike"`
						OnlyTa                    int  `json:"OnlyTa"`
						CastScreen                int  `json:"CastScreen"`
						CommentWall               int  `json:"CommentWall"`
						BulletStyle               int  `json:"BulletStyle"`
						ShowGamePlugin            int  `json:"ShowGamePlugin"`
						VSGift                    int  `json:"VSGift"`
						VSTopic                   int  `json:"VSTopic"`
						VSRank                    int  `json:"VSRank"`
						AdminCommentWall          int  `json:"AdminCommentWall"`
						CommerceComponent         int  `json:"CommerceComponent"`
						DouPlus                   int  `json:"DouPlus"`
						GamePointsPlaying         int  `json:"GamePointsPlaying"`
						Poster                    int  `json:"Poster"`
						Highlights                int  `json:"Highlights"`
						TypingCommentState        int  `json:"TypingCommentState"`
						StrokeUpDownGuide         int  `json:"StrokeUpDownGuide"`
						UpRightStatsFloatingLayer int  `json:"UpRightStatsFloatingLayer"`
						CastScreenExplicit        int  `json:"CastScreenExplicit"`
						Selection                 int  `json:"Selection"`
						IndustryService           int  `json:"IndustryService"`
						VerticalRank              int  `json:"VerticalRank"`
						EnterEffects              int  `json:"EnterEffects"`
						FansClub                  int  `json:"FansClub"`
						EmojiOutside              int  `json:"EmojiOutside"`
						CanSellTicket             int  `json:"CanSellTicket"`
						DouPlusPopularityGem      int  `json:"DouPlusPopularityGem"`
						MissionCenter             int  `json:"MissionCenter"`
						ExpandScreen              int  `json:"ExpandScreen"`
						FansGroup                 int  `json:"FansGroup"`
						Topic                     int  `json:"Topic"`
						AnchorMission             int  `json:"AnchorMission"`
						Teleprompter              int  `json:"Teleprompter"`
						SpecialStyle              struct {
							Chat struct {
								UnableStyle int    `json:"UnableStyle"`
								Content     string `json:"Content"`
								OffType     int    `json:"OffType"`
							} `json:"Chat"`
						} `json:"SpecialStyle"`
					} `json:"room_auth"`
					LiveRoomMode int `json:"live_room_mode"`
					Stats        struct {
						TotalUserDesp string `json:"total_user_desp"`
						LikeCount     int    `json:"like_count"`
						TotalUserStr  string `json:"total_user_str"`
						UserCountStr  string `json:"user_count_str"`
					} `json:"stats"`
					HasCommerceGoods bool `json:"has_commerce_goods"`
					LinkerMap        struct {
						Num1 int64 `json:"1"`
					} `json:"linker_map"`
					LinkerDetail struct {
						LinkerPlayModes             []interface{} `json:"linker_play_modes"`
						BigPartyLayoutConfigVersion int           `json:"big_party_layout_config_version"`
						AcceptAudiencePreApply      bool          `json:"accept_audience_pre_apply"`
						LinkerUILayout              int           `json:"linker_ui_layout"`
						EnableAudienceLinkmic       int           `json:"enable_audience_linkmic"`
					} `json:"linker_detail"`
				} `json:"room"`
				RoomID string `json:"roomId"`
				WebRid string `json:"web_rid"`
				Anchor struct {
					IDStr       string `json:"id_str"`
					SecUID      string `json:"sec_uid"`
					Nickname    string `json:"nickname"`
					AvatarThumb struct {
						URLList []string `json:"url_list"`
					} `json:"avatar_thumb"`
					FollowInfo struct {
						FollowStatus    int    `json:"follow_status"`
						FollowStatusStr string `json:"follow_status_str"`
					} `json:"follow_info"`
				} `json:"anchor"`
				RoomExtra struct {
					DiggColor         string `json:"digg_color"`
					PayScores         string `json:"pay_scores"`
					IsOfficialChannel bool   `json:"is_official_channel"`
				} `json:"roomExtra"`
				EnterMode        int    `json:"enter_mode"`
				QrcodeURL        string `json:"qrcode_url"`
				PartitionRoadMap struct {
				} `json:"partition_road_map"`
				RelevantRooms []interface{} `json:"relevant_rooms"`
			} `json:"roomInfo"`
			EmojiList   []interface{} `json:"emojiList"`
			EmojiReflex struct {
			} `json:"emojiReflex"`
		} `json:"roomStore"`
		LinkmicStore struct {
			ApplySource   string `json:"applySource"`
			LinkMicConfig struct {
				Config struct {
				} `json:"config"`
			} `json:"linkMicConfig"`
			LinkMicSeats struct {
				Num0 struct {
					Idx int `json:"idx"`
				} `json:"0"`
				Num1 struct {
					Idx int `json:"idx"`
				} `json:"1"`
				Num2 struct {
					Idx int `json:"idx"`
				} `json:"2"`
				Num3 struct {
					Idx int `json:"idx"`
				} `json:"3"`
				Num4 struct {
					Idx int `json:"idx"`
				} `json:"4"`
				Num5 struct {
					Idx int `json:"idx"`
				} `json:"5"`
				Num6 struct {
					Idx int `json:"idx"`
				} `json:"6"`
				Num7 struct {
					Idx int `json:"idx"`
				} `json:"7"`
				Num8 struct {
					Idx int `json:"idx"`
				} `json:"8"`
			} `json:"linkMicSeats"`
			SelectedLinkMicDevices struct {
			} `json:"selectedLinkMicDevices"`
			LinkStatus           int  `json:"linkStatus"`
			DevicesModalMode     int  `json:"devicesModalMode"`
			AudioPermission      int  `json:"audioPermission"`
			VideoPermission      int  `json:"videoPermission"`
			IsFansGuide          bool `json:"isFansGuide"`
			IsCandidate          bool `json:"isCandidate"`
			IsPlayModeNotSupport bool `json:"isPlayModeNotSupport"`
		} `json:"linkmicStore"`
		NavigationStore struct {
			RecommendNavList []interface{} `json:"recommendNavList"`
			NavigationList   []interface{} `json:"navigationList"`
		} `json:"navigationStore"`
	} `json:"initialState"`
}

type StreamData struct {
	Common struct {
		SessionID string `json:"session_id"`
		RuleIds   string `json:"rule_ids"`
	} `json:"common"`
	Data struct {
		Hd struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"hd"`
		Sd struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"sd"`
		Ld struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"ld"`
		Origin struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"origin"`
	} `json:"data"`
}
